### ISSUE TITLE
[Task] Github 공부 / 양승준

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#10]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 회원가입, 로그인 페이지 구현 및 기능 구현

### **TODO**

- [x]   github 관리 익숙해지기
- [x]   백엔드 (문기훈, 양승준) 끼리 코드 주고받기 문제없이 하기
- [x]   다른 repo를 만들어서 계속 연습하기
### **Estimated time**
> ### **`3h`**

### **Labels**

- Estimated time: `E: 3h`
- Group :  `server`
- Sprint: `Sprint2`
- Urgency: `High`
