### ISSUE TITLE
[Task] 회원가입, 로그인  / 박세현, 김윤재

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#11]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 기능 구현

### **TODO**

- [x] Footer 구현
- [x] Nav bar 구현
- [x] Modal 창 기능 구현
- [x] Login Modal 창 기능 구현
- [x]  정규식 활용하여 유효성 검사
- [x] Github merge
- [x] .svg loading bug 수정

### **Estimated time**

> ### **`12h`**

### **Labels**

- Estimated time: `E: 12h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `Middle`
