### ISSUE TITLE
[Task] Github 공부 / 문기훈

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#34]
### **ISSUE**

- Group: `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: github merge, fetch, pull request ..... study (완벽하게)

### **TODO**

- [x]  github 관리 익숙해지기
- [x]  백엔드 (문기훈, 양승준) 끼리 코드 주고받기 문제없이 하기
- [x]  다른 repo를 만들어서 계속 연습하기

### **Estimated time**

> ### **`3h`**

### **Labels**

- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint2, 3`
- Urgency: `High`
