### ISSUE TITLE
[Task] API문서, DB스키마 수정 / 문기훈, 양승준

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#44]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: API문서, DB스키마 문서 내용 수정

### **TODO**

- [ ]  API문서의 parameter, endpoint 확인 및 수정
- [ ]  DB스키마 확인 및 수정
- [ ]  Github Wiki 수정

### **Estimated time**

> ### **`1.5h`**

### **Labels**

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint3`
- Urgency: `Low`
