### ISSUE TITLE
[Task] Client component 구성 / 김윤재

### ISSUE THREAD

**Issue by yunjaekim00** [codestates/Cafe.in-first#47]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: add feature at the front-end

### **TODO**

- [x]  `<Pricing>` component List refactoring
- [x]  `<NavBar>`에 Dropdown 메뉴 추가
- [x] isLogin 성공시 Dropdown 메뉴 Show 기능
- [x] isLogin 성공시 Login과 Signup button이 MyPage와 Logout으로 변경 기능
- [x]  isLogin 성공시 Home 창이 MainPage로 전환

### **Labels**

- Estimated time: `E: 12h`
- Group : `client`
- Sprint: `Sprint__3__`
- Urgency: `High`
