### ISSUE TITLE
[Task] posts 기능 endpoint구현 / 문기훈, 양승준

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#48]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: API문서 참고 후 endpoint 분기

### **TODO**

- [x]  API문서 참고해서 적절한 endpoint 파일 만들기
- [x]  index.js 파일 수정
- [x] controllers 파일 수정

### **Estimated time**

> ### **`1.5h`**

### **Labels**

- Estimated time: `E: 1.5h`
- Group : `server`
- Sprint: `Sprint3`
- Urgency: `Middle`,
