### ISSUE TITLE
[Task] cafe-list 기능 구현 / 문기훈

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#49]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: DB에서 메인페이지 게시물 받아오기

### **TODO**

- [x]  모든 게시물 sequelize 함수로 받아오기
- [x]  프론트엔드 (클라이언트) 단으로 넘겨 주는 데이터 알아내기
- [x]  해시태그와 게시물 모두 데이터로 받기

### **Estimated time**

> ### **`2h`**

### **Labels**

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `Middle`
