### ISSUE TITLE
[TASK]: Mainpage 작성　/박세현,김윤재

### ISSUE THREAD

**Issue by park0866** [codestates/Cafe.in-first#50]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: modal , mainpage 작성

### **TODO**
- [x]  nav작성 
- [x]  dropdown작성  (styled-components)
- [x]  mainpage 작성 (styled-components)
- [x]  modal 카카오 edit
- [ ]  Github Wiki 수정 
- [x]  회원탈퇴 버그 수정
- [x] 리스트 반응형 자동 줄바뀜 기능 구현

### **Estimated time**

> ### **`8h`**

### **Labels**

- Estimated time: `E: 8h`
- Group : `Client`
- Sprint: `Sprint3`
- Urgency: `Low`
