### ISSUE TITLE
[Task] 서버가 닫히면 클라이언트 자동 로그아웃 / 문기훈

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#57]
### **ISSUE**

- Group: `server`
- Type: `bug`, `feature`
- Detail: 예외사항 확인 및 처리하기

### **TODO**

- [x]  토큰 인증방식에서 서버가 닫히면 토큰을 클라이언트가 들고 있기 때문에 로그아웃 처리가 안 되는데 방법 찾기
- [x]  찾은 방법을 구체화 후 코드 작성
- [x]  포스트맨에서 확인 및 테스트

### **Estimated time**

> ### **`3h`**

### **Labels**

- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency:`Low`
