### ISSUE TITLE
[Task] backend 코드 주석 명세 / 문기훈

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#63]
### **ISSUE**

- Group: `server`
- Type: `feature`, `explain`
- Detail: 각각의 기능 코드에 주석을 달아서 가독성 높이기 

### **TODO**

- [x]  users 기능 코드 주석 달기 -> 기능 구현 목적 및 의의 명세
- [x]  posts 기능 코드 주석 달기 -> 기능 구현 목적 및 의의 명세
- [x]  db sequelize 기능 (조인) 

### **Estimated time**

> ### **`2h`**

### **Labels**

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint3`
- Urgency: `Low`
