### ISSUE TITLE
[Task] Backend 코드 모듈화 1차 / 문기훈

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#65]
### **ISSUE**

- Group: `server`
- Type: `cleaning code`
- Detail: 반복 함수, 선언, 기능은 모듈화를 한다.

### **TODO**

- [x]  반복 선언, 함수, 기능 찾기
- [x]  모듈화 파일을 만들어서 객체 형식으로 코드 작성
- [x]  모듈화 된 기능을 사용 및 테스트

### **Estimated time**

> ### **`3h`**

### **Labels**

- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint3`
- Urgency: `Low`
