### ISSUE TITLE
[Task] post 픽스 / 양승준

### ISSUE THREAD

**Issue by Tarosism** [codestates/Cafe.in-first#85]
### **ISSUE**

- Group: `server`, `sr`
- Type: `bug`, `feature`
- Detail: 

### **TODO**

- [x]  해시태그 클릭 시 게시글이 가지고 있는 해시태그를 제외하지 않고 모두 포함시킴
- [x]  해시태그를 한 번 더 클릭 시 아무 일도 일어나면 안됨. 아무 일도
- ~~왜 지금은 또 되고 그러냐 그러지 마라진짜~~
- 완전히 fix완료
- [ ]  (Option) target 해시태그 중복 선택 시 요청을 보내지 않습니다
- [x]  (Option or Need to redux) 검색 옵션 초기화
- 버튼이 없이 할 수 있는 방법은 없을까?
- [ ]  (Option) ~~비로그인 상태에서 main dummy 요청~~
- seeder에 스트레스 받기 싫어서 포기. 필요해지면 하겠음
- [ ]  (Option) 카페 정보 열람 가능? 가능? 가능????
- 불가능. antd쓰면 가능ㅎ

### **Estimated time**

> Pick one
> 

### **Labels**

- Estimated time: 
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
