### ISSUE TITLE
[Task] 프레젠테이션자료 제작 / 문기훈

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#89]
### **ISSUE**

- Group: `server`
- Type: `Presentation`
- Detail: 프레젠테이션 준비

### **TODO**

- [ ]  프레젠테이션 플로우 구상 및 구체화
- [ ]  기능 구현 gif파일로 만들기
- [ ]  PPT에 gif파일 첨부 (ubuntu -> window) window에서 작업
- [ ]  PPT제작 (window)
- [ ]  대본 제작

### **Estimated time**

> ### **`3h`**

### **Labels**

- Estimated time: `E: 3h`
- Group : `Team`
- Urgency: `Middle`
