### ISSUE TITLE
[Task] 프레젠테이션 녹화 및 제출 / Team

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in-first#90]
### **ISSUE**

- Group: `Team`
- Type: `Presentation`
- Detail: 프레젠테이션 녹화 (라이브 X)

### **TODO**

- [ ]  발표자 문기훈 -> 7분에 맞는 프레젠테이션 녹화
- [ ]  팀원 간 시청 후 수정 및 피드백
- [ ]  최종 프레젠테이션 녹화본 제출하기

### **Estimated time**

> ### **`2h`**

### **Labels**

- Estimated time: `E: 2h`
- Group : `Team`
- Urgency:  `Middle`
